---
# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-case-conflict
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable
      - id: check-yaml
      - id: detect-private-key
      - id: trailing-whitespace
  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports
        args: ['--application-directories','lib:src']
        exclude: '^tests/'
  - repo: https://github.com/pycqa/isort
    rev: 5.11.4
    hooks:
      - id: isort
        args: ['--add-import', 'from __future__ import annotations']
  - repo: local
    hooks:
      - id: black
        name: check code is correctly formatted
        entry: poetry run task black
        pass_filenames: false
        language: system
      - id: mypy
        name: check code passes static type analysis
        entry: poetry run task mypy
        pass_filenames: false
        language: system
      - id: pylint
        name: check code passes static analyser
        entry: poetry run task pylint
        pass_filenames: false
        language: system
