[tool.poetry]
name = "blcli"
version = "0.1.0"
description = ""
authors = ["Nathan O'Sullivan <nathan.osullivan@mammoth.com.au>"]
readme = "README.md"
packages = [{include = "blcli", from = "src"}]

[tool.poetry.dependencies]
python = "^3.8"
terminaltables = "^3.1.10"

[tool.poetry.scripts]
bl = "blcli:main"

[tool.poetry.group.dev.dependencies]
openapi-python-client = "^0.11.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
